# This is a basic workflow to help you get started with Actions

name: Windows Build CI

# Controls when the workflow will run
on: [push, pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Setup Android NDK
        uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: r15c

      - name: Setup Java JDK
        uses: actions/setup-java@v1
        with:
          java-version: '11'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v1
      
      - uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.2.5
      # Runs a set of commands using the runners shell
      - name: script run line haha
        run: |
          # choco install haxe --version 4.2.5 -y
          # RefreshEnv
          sudo add-apt-repository ppa:haxe/releases -y
          sudo apt-get update
          sudo apt-get install gcc-multilib g++-multilib haxe -y
          mkdir "%HAXELIB_ROOT%"
          haxelib setup "%HAXELIB_ROOT%"
          haxelib install lime 7.9.0
          # RefreshEnv
          haxelib install openfl 9.1.0
          haxelib install flixel 4.9.0
          haxelib run lime setup flixel
          haxelib run lime setup --quiet
          haxelib install flixel-tools 1.5.1
          haxelib install flixel-addons 2.10.0
          haxelib install flixel-ui 2.3.3
          haxelib install hscript
          haxelib git faxe https://github.com/uhrobots/faxe
          haxelib git polymod https://github.com/MasterEric/polymod.git
          haxelib git discord_rpc https://github.com/Aidan63/linc_discord-rpc
          haxelib git extension-webm https://github.com/brusakas/extension-webm
          haxelib git linc_luajit https://github.com/nebulazorua/linc_luajit.git
          haxelib git hxvm-luajit https://github.com/nebulazorua/hxvm-luajit
          haxelib install actuate 
          haxelib list

      - name: Setup Lime
        run: |
          haxelib run lime setup -alias -y
          haxelib run lime config ANDROID_SDK $ANDROID_HOME
          haxelib run lime config ANDROID_NDK_ROOT $ANDROID_NDK_HOME
          haxelib run lime config JAVA_HOME $JAVA_HOME
          haxelib run lime config ANDROID_SETUP true
          haxelib set lime 7.9.0
          haxelib set openfl 9.1.0
        env:
          ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}
          
      - name: Compile
          haxelib run lime build android
          
      - uses: actions/upload-artifact@v2
        with:
          name: Android Build
          path: export_sunday/release/android/bin/app/build/outputs/apk/debug
